// Generated by `npm run db:bundle`: do not edit.

/** The last migration this code expects in the database (supabase/migrations). */
export const LATEST_MIGRATION = '0048_alumni_without_experience.sql';
