import { readdirSync, readFileSync } from 'node:fs';
import path from 'node:path';

const MIGRATION_QUOTE = '$migration$';
const BLOCK_QUOTE = '$install$';

export function migrationFiles(migrationsDir: string): string[] {
  return readdirSync(migrationsDir)
    .filter((file) => /^\d{4}_[a-z0-9_]+\.sql$/.test(file))
    .sort();
}

/**
 * Every migration in one script for Supabase's SQL Editor: one paste installs a new project or
 * brings an installed one up to date. Each migration runs only if stayput.schema_migrations does
 * not list it yet, then is recorded there, exactly as `npm run db:migrate` does: the two can be
 * mixed. The whole paste is one transaction (all or nothing).
 */
export function buildInstallSql(migrationsDir: string, options: { upTo?: string } = {}): string {
  const files = migrationFiles(migrationsDir).filter(
    (file) => !options.upTo || file <= options.upTo,
  );
  const parts = [
    `-- StayPut: the whole database schema, for a new Supabase project or to update one.
-- Generated from supabase/migrations (${files[0]} to ${files.at(-1)}) by \`npm run db:bundle\`:
-- do not edit.
--
-- Supabase -> SQL Editor -> New query -> paste this whole file -> Run. Only the migrations not
-- applied yet run (stayput.schema_migrations lists them), so paste it again after each update.
-- It runs in one transaction: on any error, nothing is applied.

begin;

create schema if not exists stayput;
create table if not exists stayput.schema_migrations (
  name text primary key,
  applied_at timestamptz not null default now()
);
alter table stayput.schema_migrations enable row level security;`,
  ];
  for (const file of files) {
    const body = readFileSync(path.join(migrationsDir, file), 'utf8').trim();
    for (const quote of [MIGRATION_QUOTE, BLOCK_QUOTE]) {
      if (body.includes(quote)) throw new Error(`${file} must not contain ${quote}`);
    }
    parts.push(
      `-- ${'='.repeat(90)}
-- ${file}
-- ${'='.repeat(90)}

do ${BLOCK_QUOTE}
begin
  if exists (select 1 from stayput.schema_migrations where name = '${file}') then
    raise notice 'already applied: ${file}';
    return;
  end if;
  execute ${MIGRATION_QUOTE}
${body}
${MIGRATION_QUOTE};
  insert into stayput.schema_migrations (name) values ('${file}');
end ${BLOCK_QUOTE};`,
    );
  }
  parts.push('commit;');
  return `${parts.join('\n\n')}\n`;
}

/** apps/worker/src/schema-version.ts: the last migration, which /health expects to find. */
export function buildSchemaVersion(migrationsDir: string): string {
  const latest = migrationFiles(migrationsDir).at(-1);
  if (!latest) throw new Error('no migration found');
  return `// Generated by \`npm run db:bundle\`: do not edit.

/** The last migration this code expects in the database (supabase/migrations). */
export const LATEST_MIGRATION = '${latest}';
`;
}
